# Generated by Django 5.2.4 on 2025-09-08 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام فصل')),
                ('order', models.PositiveIntegerField(verbose_name='ترتیب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'فصل\u200cها',
                'ordering': ['subject', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام زیربخش')),
                ('order', models.PositiveIntegerField(verbose_name='ترتیب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='knowledge.chapter', verbose_name='فصل')),
            ],
            options={
                'verbose_name': 'زیربخش',
                'verbose_name_plural': 'زیربخش\u200cها',
                'ordering': ['chapter', 'order'],
                'unique_together': {('chapter', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کتاب')),
                ('grade', models.IntegerField(verbose_name='پایه تحصیلی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='subjects/', verbose_name='تصویر جلد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'کتاب درسی',
                'verbose_name_plural': 'کتاب\u200cهای درسی',
                'ordering': ['grade', 'name'],
                'unique_together': {('name', 'grade')},
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='knowledge.subject', verbose_name='کتاب'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام مبحث')),
                ('order', models.PositiveIntegerField(verbose_name='ترتیب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('difficulty', models.CharField(choices=[('beginner', 'مبتدی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته'), ('expert', 'تخصصی')], default='intermediate', max_length=20, verbose_name='سطح دشواری')),
                ('tags', models.CharField(blank=True, help_text='تگ\u200cها را با کاما جدا کنید', max_length=500, verbose_name='تگ\u200cها')),
                ('estimated_study_time', models.PositiveIntegerField(default=30, verbose_name='زمان تخمینی مطالعه (دقیقه)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisites', models.ManyToManyField(blank=True, help_text='مباحثی که باید قبل از این مبحث یاد گرفته شوند', to='knowledge.topic', verbose_name='پیش\u200cنیازها')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='knowledge.section', verbose_name='زیربخش')),
            ],
            options={
                'verbose_name': 'مبحث',
                'verbose_name_plural': 'مباحث',
                'ordering': ['section', 'order'],
                'unique_together': {('section', 'order')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('subject', 'order')},
        ),
        migrations.CreateModel(
            name='StudentTopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests_taken', models.PositiveIntegerField(default=0, verbose_name='تعداد آزمون\u200cهای گرفته\u200cشده')),
                ('total_score', models.FloatField(default=0, verbose_name='مجموع امتیاز')),
                ('best_score', models.FloatField(default=0, verbose_name='بهترین امتیاز')),
                ('skill_level', models.FloatField(default=0, verbose_name='سطح مهارت')),
                ('is_mastered', models.BooleanField(default=False, verbose_name='تسلط یافته')),
                ('mastery_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تسلط')),
                ('first_attempt', models.DateTimeField(auto_now_add=True, verbose_name='اولین تلاش')),
                ('last_attempt', models.DateTimeField(auto_now=True, verbose_name='آخرین تلاش')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progresses', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progresses', to='knowledge.topic', verbose_name='مبحث')),
            ],
            options={
                'verbose_name': 'پیشرفت مبحثی',
                'verbose_name_plural': 'پیشرفت\u200cهای مبحثی',
                'ordering': ['-last_attempt'],
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
