# Generated by Django 5.2.4 on 2025-09-10 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_file_content_type'),
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='book_file',
            field=models.ForeignKey(blank=True, help_text='فایل PDF کتاب درسی', limit_choices_to={'content_type': 'book'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_books', to='contents.file', verbose_name='فایل کتاب'),
        ),
    ]
