# Generated by Django 5.2.4 on 2025-09-11 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_subject_book_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['topic_category', 'order'], 'verbose_name': 'مبحث', 'verbose_name_plural': 'مباحث'},
        ),
        migrations.AlterField(
            model_name='topic',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_topics', to='knowledge.section', verbose_name='زیربخش (قدیمی)'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام درس')),
                ('order', models.PositiveIntegerField(verbose_name='ترتیب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='knowledge.section', verbose_name='زیربخش')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'درس\u200cها',
                'ordering': ['section', 'order'],
                'unique_together': {('section', 'order')},
            },
        ),
        migrations.CreateModel(
            name='TopicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام دسته موضوع')),
                ('order', models.PositiveIntegerField(verbose_name='ترتیب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_categories', to='knowledge.lesson', verbose_name='درس')),
            ],
            options={
                'verbose_name': 'دسته موضوع',
                'verbose_name_plural': 'دسته\u200cهای موضوع',
                'ordering': ['lesson', 'order'],
                'unique_together': {('lesson', 'order')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='knowledge.topiccategory', verbose_name='دسته موضوع'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('topic_category', 'order')},
        ),
    ]
