# Generated by Django 5.2.4 on 2025-07-30 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(help_text='Remote or CDN file identifier (e.g., ArvanCloud UID)', max_length=1024)),
                ('file', models.FileField(help_text='Uploaded file (PDF or MP4)', upload_to='documents/')),
                ('file_type', models.CharField(choices=[('video/mp4', 'Video'), ('application/pdf', 'PDF')], help_text='MIME type of the file', max_length=50)),
                ('title', models.CharField(help_text='Human-readable title of the file', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(help_text='The course this file is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.course')),
                ('session', models.ForeignKey(blank=True, help_text='The specific course session, if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.coursesession')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ['-created_at'],
            },
        ),
    ]
