# Generated by Django 5.2.4 on 2025-07-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='arvan_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, help_text='Uploaded file (PDF or MP4)', null=True, upload_to='documents/'),
        ),
    ]
