# Generated by Django 5.2.4 on 2025-08-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_file_arvan_url_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='content_type',
            field=models.CharField(choices=[('book', 'Book'), ('test', 'Test'), ('note', 'Note')], default='note', help_text="Content type of the file (e.g., 'Book', 'Test', 'Note')", max_length=50),
        ),
    ]
