# Generated by Django 5.2.4 on 2025-09-11 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_file_content_type'),
        ('courses', '0006_classcategory_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='course',
            field=models.ForeignKey(blank=True, help_text='The course this file is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.course'),
        ),
    ]
