# Generated by Django 5.2.4 on 2025-10-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_alter_file_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the image', max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Optional description of the image', verbose_name='Description')),
                ('image', models.ImageField(help_text='Gallery image file', upload_to='gallery/', verbose_name='Image')),
                ('is_published', models.BooleanField(default=True, help_text='Whether this image is published and visible to users', verbose_name='Is Published')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)', verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
