# Generated by Django 5.2.4 on 2025-10-07 13:02

import api.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(help_text='Gallery image file', storage=api.storage.PublicMediaStorage(), upload_to='gallery/', verbose_name='Image'),
        ),
    ]
