# Generated by Django 5.2.4 on 2025-10-21 10:32

import api.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_alter_galleryimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the official book', max_length=255, verbose_name='Title')),
                ('publication_year', models.PositiveIntegerField(help_text='Year the book was published', verbose_name='Publication Year')),
                ('cover_image', models.ImageField(help_text='Cover image of the book', storage=api.storage.PublicMediaStorage(), upload_to='official_books/covers/', verbose_name='Cover Image')),
                ('pdf_file', models.FileField(blank=True, help_text='PDF file of the book', null=True, storage=api.storage.PublicMediaStorage(), upload_to='official_books/pdfs/', verbose_name='PDF File')),
                ('file_url', models.URLField(blank=True, max_length=500, null=True)),
                ('grade', models.CharField(choices=[('ten', 'دهم'), ('eleven', 'یازدهم'), ('twelve', 'دوازدهم')], default='ten', max_length=20, verbose_name='نوع آزمون')),
                ('subject', models.CharField(choices=[('mathematics', 'ریاضی'), ('experimental_sciences', 'علوم تجربی'), ('humanities', 'علوم انسانی'), ('foreign_languages', 'زبان\u200cهای خارجی')], default='mathematics', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Official Book',
                'verbose_name_plural': 'Official Books',
                'ordering': ['-publication_year', 'title'],
            },
        ),
    ]
