# Generated by Django 5.2.4 on 2025-10-26 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_officialbook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='files_explicit', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموزان مرتبط'),
        ),
    ]
