# Generated by Django 5.2.4 on 2026-06-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='ref_id',
            new_name='ref_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='authority',
        ),
        migrations.AddField(
            model_name='payment',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='track_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.BigIntegerField(),
        ),
    ]
