# Generated by Django 5.2.4 on 2026-08-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_payment_allowed_cards_payment_check_mobile_with_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
