# Generated by Django 5.2.4 on 2026-08-09 15:47

import django.db.models.deletion
import finance.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_order_order_code_transaction_transaction_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.CreateModel(
            name='SMSNotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تنظیمات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('message_type', models.CharField(choices=[('bulk', 'Bulk SMS'), ('verify', 'Pattern SMS')], default='bulk', max_length=20, verbose_name='نوع پیامک')),
                ('template_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه الگوی ارسال')),
                ('template_parameters', models.JSONField(blank=True, default=dict, help_text='یک دیکشنری از نام پارامتر به یکی از متغیرهای قالب سفارش', verbose_name='پارامترهای الگو')),
                ('product_types', models.JSONField(blank=True, default=list, help_text="خالی بگذارید برای همه نوع محصولات. مثال: ['course', 'book', 'file']", verbose_name='نوع محصولات')),
                ('min_order_amount', models.PositiveIntegerField(blank=True, help_text='فقط سفارش\u200cهایی با مبلغ بالاتر از این مقدار', null=True, verbose_name='حداقل مبلغ سفارش (تومان)')),
                ('trigger_statuses', models.JSONField(default=finance.models.default_sms_trigger_statuses, help_text='چه وضعیت\u200cهایی باعث ارسال پیامک شود', verbose_name='وضعیت سفارش برای ارسال')),
                ('template_text', models.TextField(help_text='متن پیامک با متغیرهای: {order_code}, {customer_name}, {customer_phone}, {total_amount}, {product_titles}, {product_types}, {order_date}, {items_count}', verbose_name='متن پیامک')),
                ('custom_phone_numbers', models.JSONField(blank=True, default=list, help_text='لیست شماره\u200cهای موبایل (فرمت: 09xxxxxxxxx)', verbose_name='شماره تلفن\u200cهای سفارشی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('admin_users', models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['admin', 'finance']}, related_name='sms_notification_configs', to=settings.AUTH_USER_MODEL, verbose_name='کاربران ادمین/مالی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sms_configs', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
            ],
            options={
                'verbose_name': 'تنظیمات گزارش خودکار SMS',
                'verbose_name_plural': 'گزارش\u200cهای خودکار SMS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('provider_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='finance.smsnotificationconfig')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='finance.order')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='finance_sms_status_31d5c9_idx')],
            },
        ),
    ]
