# Generated by Django 5.2.4 on 2026-08-06 09:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmessage_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='گفتگوی جدید', max_length=255, verbose_name='عنوان گفتگو')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='پین شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_conversations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گفتگوی هوش مصنوعی',
                'verbose_name_plural': 'گفتگوهای هوش مصنوعی',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'کاربر'), ('assistant', 'هوش مصنوعی'), ('system', 'سیستم')], max_length=10, verbose_name='نقش')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('model_tier', models.PositiveSmallIntegerField(default=2, verbose_name='تییر مدل')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مدل')),
                ('reasoning', models.TextField(blank=True, null=True, verbose_name='استدلال مدل')),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='توکن مصرفی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.aiconversation', verbose_name='گفتگو')),
            ],
            options={
                'verbose_name': 'پیام هوش مصنوعی',
                'verbose_name_plural': 'پیام\u200cهای هوش مصنوعی',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ai_attachments/', verbose_name='فایل')),
                ('attachment_type', models.CharField(choices=[('image', 'تصویر'), ('pdf', 'PDF'), ('text', 'متن')], max_length=10, verbose_name='نوع فایل')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='نام اصلی')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='حجم فایل')),
                ('page_count', models.PositiveIntegerField(default=0, verbose_name='تعداد صفحات')),
                ('extracted_text', models.TextField(blank=True, verbose_name='متن استخراج شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.aimessage', verbose_name='پیام')),
            ],
            options={
                'verbose_name': 'پیوست هوش مصنوعی',
                'verbose_name_plural': 'پیوست\u200cهای هوش مصنوعی',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('scholar', 'Scholar'), ('genius', 'Genius')], default='basic', max_length=10, verbose_name='پلن اشتراک')),
                ('daily_tier1_used', models.PositiveIntegerField(default=0, verbose_name='مصرف روزانه Tier 1')),
                ('daily_tier2_used', models.PositiveIntegerField(default=0, verbose_name='مصرف روزانه Tier 2')),
                ('daily_tier3_used', models.PositiveIntegerField(default=0, verbose_name='مصرف روزانه Tier 3')),
                ('daily_pdf_used', models.PositiveIntegerField(default=0, verbose_name='مصرف روزانه PDF')),
                ('daily_image_used', models.PositiveIntegerField(default=0, verbose_name='مصرف روزانه تصویر')),
                ('last_reset_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ آخرین ریست')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_subscription', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اشتراک هوش مصنوعی',
                'verbose_name_plural': 'اشتراک\u200cهای هوش مصنوعی',
            },
        ),
    ]
