# Generated by Django 5.2.4 on 2025-09-15 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_verificationcode_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^09\\d{9}$', 'Enter a valid 11-digit Iranian phone number')]),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='type',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='email', max_length=5),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
