# Generated by Django 5.2.4 on 2025-10-26 15:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_limit', models.PositiveIntegerField(default=50, verbose_name='محدودیت تعداد سوالات')),
                ('access_duration', models.DateTimeField(default=datetime.datetime(2026, 10, 26, 15, 13, 4, 702788, tzinfo=datetime.timezone.utc), verbose_name='مدت زمان دسترسی')),
                ('model', models.CharField(default='gemini', max_length=50, verbose_name='مدل زبانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_access', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دسترسی هوش مصنوعی',
                'verbose_name_plural': 'دسترسی\u200cهای هوش مصنوعی',
            },
        ),
    ]
