# Generated by Django 5.2.4 on 2025-10-30 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_aiaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiaccess',
            name='access_duration',
            field=models.DateTimeField(default=datetime.datetime(2026, 10, 30, 16, 18, 54, 374196, tzinfo=datetime.timezone.utc), verbose_name='مدت زمان دسترسی'),
        ),
    ]
