# Generated by Django 5.2.4 on 2025-11-20 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_aiaccess_access_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiaccess',
            name='access_duration',
            field=models.DateTimeField(default=datetime.datetime(2026, 11, 20, 16, 9, 19, 387032, tzinfo=datetime.timezone.utc), verbose_name='مدت زمان دسترسی'),
        ),
    ]
