# Generated by Django 5.2.4 on 2026-08-05 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_aiaccess_access_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiaccess',
            name='access_duration',
            field=models.DateTimeField(default=datetime.datetime(2027, 8, 5, 12, 5, 10, 110906, tzinfo=datetime.timezone.utc), verbose_name='مدت زمان دسترسی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('support', 'Support'), ('content_creator', 'Content Creator'), ('finance', 'Finance')], default='student', max_length=20),
        ),
    ]
