# Generated by Django 5.2.4 on 2026-08-15 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_aiaccess_access_duration_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiaccess',
            name='access_duration',
            field=models.DateTimeField(default=datetime.datetime(2027, 8, 15, 20, 50, 2, 759165, tzinfo=datetime.timezone.utc), verbose_name='مدت زمان دسترسی'),
        ),
    ]
