# Generated by Django 5.2.4 on 2026-08-15 21:49

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_aiaccess_access_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiaccess',
            name='access_duration',
            field=models.DateTimeField(default=accounts.models.default_ai_access_duration, verbose_name='مدت زمان دسترسی'),
        ),
    ]
