# Generated by Django 5.2.4 on 2025-08-15 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_add_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursesession',
            unique_together=set(),
        ),
    ]
