# Generated by Django 5.2.4 on 2025-10-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_rtmp_key_course_rtmp_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rtmp_url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
