# Generated by Django 5.2.4 on 2025-10-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_is_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='live_iframe',
            field=models.TextField(blank=True, help_text='کد iframe برای نمایش پخش زنده', null=True),
        ),
    ]
