# Generated by Django 5.2.4 on 2025-10-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_live_iframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='chat_mode',
            field=models.CharField(choices=[('public', 'عمومی - همه پیام\u200cها قابل مشاهده'), ('private', 'خصوصی - فقط پیام معلم قابل مشاهده')], default='public', help_text='حالت نمایش چت برای دانش\u200cآموزان', max_length=20),
        ),
    ]
