# Generated by Django 5.2.4 on 2025-10-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_chat_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stream_id',
            field=models.CharField(blank=True, help_text='ArvanCloud Stream ID for live streaming', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='live_iframe',
            field=models.TextField(blank=True, default='', help_text='کد iframe برای نمایش پخش زنده', null=True),
        ),
    ]
