# Generated by Django 5.2.4 on 2026-08-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_stream_id_alter_course_live_iframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='spotplayer_course_id',
            field=models.CharField(blank=True, help_text='شناسه دوره در پنل اسپات\u200cپلیر (SpotPlayer course _id)', max_length=100, null=True),
        ),
    ]
