# Generated by Django 5.2.4 on 2025-10-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, help_text='L x W x H in cm', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_shipping',
            field=models.BooleanField(default=False, help_text='True for physical products'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_cost',
            field=models.IntegerField(default=0, help_text='Shipping cost in Tomans'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, help_text='Available stock for physical products'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in grams', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('file', 'File'), ('course', 'Course'), ('test', 'Test'), ('book', 'Book'), ('notebook', 'Notebook'), ('pamphlet', 'Pamphlet'), ('stationery', 'Stationery')]),
        ),
    ]
