# Generated by Django 5.2.4 on 2025-08-12 08:22

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_alter_test_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttestsession',
            name='active',
        ),
        migrations.AddField(
            model_name='studenttestsession',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 12, 8, 22, 11, 2553, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studenttestsession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenttestsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='studenttestsession',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='studenttestsession',
            index=models.Index(fields=['user', 'test'], name='tests_stude_user_id_f184cc_idx'),
        ),
        migrations.AddIndex(
            model_name='studenttestsession',
            index=models.Index(fields=['status'], name='tests_stude_status_2d7509_idx'),
        ),
        migrations.AddConstraint(
            model_name='studenttestsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'test'), name='unique_active_session_per_test'),
        ),
    ]
