# Generated by Django 5.2.4 on 2025-08-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_studenttestsessionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttestsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', max_length=20),
        ),
    ]
