# Generated by Django 5.2.4 on 2025-08-18 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_alter_studenttestsession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarykey',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_keys', to='tests.test'),
        ),
    ]
