# Generated by Django 5.2.4 on 2025-08-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_alter_primarykey_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='answer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
