# Generated by Django 5.2.4 on 2025-08-21 17:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_file_content_type'),
        ('courses', '0006_classcategory_course_category'),
        ('tests', '0010_alter_studentanswer_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['-created_at'], 'verbose_name': 'آزمون', 'verbose_name_plural': 'آزمون\u200cها'},
        ),
        migrations.AddField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='test',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='test',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='courses.course', verbose_name='دوره'),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.DurationField(verbose_name='مدت زمان آزمون'),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_time',
            field=models.DateTimeField(verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='test',
            name='frequency',
            field=models.CharField(max_length=100, verbose_name='تکرار'),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام آزمون'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pdf_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.file', verbose_name='فایل PDF'),
        ),
        migrations.AlterField(
            model_name='test',
            name='start_time',
            field=models.DateTimeField(verbose_name='زمان شروع'),
        ),
        migrations.AlterField(
            model_name='test',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='معلم'),
        ),
        migrations.CreateModel(
            name='TestCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام مجموعه آزمون')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی')),
                ('courses', models.ManyToManyField(blank=True, related_name='test_collections', to='courses.course', verbose_name='دوره\u200cهای مرتبط')),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_test_collections', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('purchased_by', models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='purchased_test_collections', to=settings.AUTH_USER_MODEL, verbose_name='خریداران مستقیم')),
            ],
            options={
                'verbose_name': 'مجموعه آزمون',
                'verbose_name_plural': 'مجموعه\u200cهای آزمون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='test',
            name='test_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='tests.testcollection', verbose_name='مجموعه آزمون'),
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests_completed', models.PositiveIntegerField(default=0, verbose_name='آزمون\u200cهای تکمیل شده')),
                ('total_tests', models.PositiveIntegerField(default=0, verbose_name='کل آزمون\u200cها')),
                ('average_score', models.FloatField(default=0.0, verbose_name='میانگین نمرات')),
                ('last_test_date', models.DateTimeField(blank=True, null=True, verbose_name='آخرین آزمون')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='test_progresses', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
                ('test_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progresses', to='tests.testcollection', verbose_name='مجموعه آزمون')),
            ],
            options={
                'verbose_name': 'پیشرفت دانش\u200cآموز',
                'verbose_name_plural': 'پیشرفت\u200cهای دانش\u200cآموزان',
                'ordering': ['-updated_at'],
                'unique_together': {('student', 'test_collection')},
            },
        ),
        migrations.CreateModel(
            name='TestCollectionPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ خرید')),
                ('price_paid', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ پرداختی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='test_collection_purchases', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
                ('test_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='tests.testcollection', verbose_name='مجموعه آزمون')),
            ],
            options={
                'verbose_name': 'خرید مجموعه آزمون',
                'verbose_name_plural': 'خریدهای مجموعه آزمون',
                'ordering': ['-purchase_date'],
                'unique_together': {('student', 'test_collection')},
            },
        ),
    ]
