# Generated by Django 5.2.4 on 2025-08-21 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_alter_test_options_test_created_at_test_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcollection',
            name='price',
        ),
        migrations.RemoveField(
            model_name='testcollection',
            name='purchased_by',
        ),
        migrations.DeleteModel(
            name='TestCollectionPurchase',
        ),
    ]
