# Generated by Django 5.2.4 on 2025-08-21 18:06

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_remove_testcollection_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprogress',
            options={'ordering': ['-last_activity'], 'verbose_name': 'پیشرفت دانش\u200cآموز', 'verbose_name_plural': 'پیشرفت دانش\u200cآموزان'},
        ),
        migrations.AlterUniqueTogether(
            name='studentprogress',
            unique_together={('test_collection', 'student')},
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='completed_tests',
            field=models.PositiveIntegerField(default=0, verbose_name='آزمون\u200cهای تکمیل\u200cشده'),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='تکمیل\u200cشده'),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین فعالیت'),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ شروع'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='total_score',
            field=models.FloatField(default=0, verbose_name='مجموع امتیاز'),
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='average_score',
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='last_test_date',
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='tests_completed',
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='total_tests',
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='updated_at',
        ),
    ]
