# Generated by Django 5.2.4 on 2025-08-21 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_alter_studentprogress_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='course',
        ),
        migrations.AlterField(
            model_name='test',
            name='test_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='tests.testcollection', verbose_name='مجموعه آزمون'),
        ),
    ]
