# Generated by Django 5.2.4 on 2025-08-21 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_remove_test_course_alter_test_test_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='tests.testcollection', verbose_name='مجموعه آزمون'),
        ),
    ]
