# Generated by Django 5.2.4 on 2025-08-22 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_file_content_type'),
        ('tests', '0018_alter_test_test_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='answers_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_answers_file', to='contents.file', verbose_name='فایل پاسخنامه'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pdf_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_file', to='contents.file', verbose_name='فایل PDF'),
        ),
    ]
