# Generated by Django 5.2.4 on 2025-09-08 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        ('tests', '0019_test_answers_file_alter_test_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='مبحث درخت دانشی که این آزمون به آن مربوط است', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_tests', to='knowledge.topic', verbose_name='مبحث مرتبط'),
        ),
    ]
