# Generated by Django 5.2.4 on 2025-09-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0020_test_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('scheduled', 'آزمون زمان\u200cبندی شده'), ('topic_based', 'آزمون مبحثی آزاد'), ('practice', 'آزمون تمرینی')], default='scheduled', max_length=20, verbose_name='نوع آزمون'),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='فقط برای آزمون\u200cهای زمان\u200cبندی شده الزامی است', null=True, verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='test',
            name='frequency',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تکرار'),
        ),
        migrations.AlterField(
            model_name='test',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='فقط برای آزمون\u200cهای زمان\u200cبندی شده الزامی است', null=True, verbose_name='زمان شروع'),
        ),
    ]
