# Generated by Django 5.2.4 on 2025-09-17 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_alter_folder_id'),
        ('tests', '0023_test_folders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=500, verbose_name='متن گزینه')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب گزینه')),
                ('option_image', models.ImageField(blank=True, null=True, upload_to='options/', verbose_name='تصویر گزینه')),
            ],
            options={
                'verbose_name': 'گزینه',
                'verbose_name_plural': 'گزینه\u200cها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='متن سوال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('difficulty_level', models.CharField(choices=[('easy', 'ساده'), ('medium', 'متوسط'), ('hard', 'دشوار')], default='medium', max_length=10, verbose_name='سطح دشواری')),
                ('correct_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correct_for_questions', to='tests.option', verbose_name='گزینه صحیح')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('folders', models.ManyToManyField(blank=True, related_name='questions', to='knowledge.folder', verbose_name='پوشه\u200cها')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
            },
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tests.question', verbose_name='سوال مرتبط'),
        ),
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='question_images/', verbose_name='تصویر')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='متن جایگزین')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب تصویر')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tests.question', verbose_name='سوال مرتبط')),
            ],
            options={
                'verbose_name': 'تصویر سوال',
                'verbose_name_plural': 'تصاویر سوال',
                'ordering': ['order'],
            },
        ),
    ]
