# Generated by Django 5.2.4 on 2025-09-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0025_question_is_active_question_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='detailed_solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
