# Generated by Django 5.2.4 on 2025-09-19 12:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0026_question_detailed_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='public_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, verbose_name='شناسه عمومی'),
        ),
    ]
