# Generated by Django 5.2.4 on 2025-09-19 12:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0027_question_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='شناسه عمومی'),
        ),
    ]
