# Generated by Django 5.2.4 on 2025-09-19 14:01

import tests.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_alter_folder_id'),
        ('tests', '0028_alter_question_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'verbose_name': 'سوال', 'verbose_name_plural': 'سوالات'},
        ),
        migrations.AlterField(
            model_name='question',
            name='public_id',
            field=models.CharField(default=tests.models.generate_secure_question_id, help_text='شناسه شش\u200cکاراکتری با رقم کنترل برای نمایش عمومی', max_length=6, unique=True, verbose_name='شناسه عمومی'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['public_id'], name='tests_quest_public__2f957c_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty_level'], name='tests_quest_difficu_1b38ff_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_at'], name='tests_quest_created_0bebfc_idx'),
        ),
    ]
