# Generated by Django 5.2.4 on 2025-09-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0029_alter_question_options_alter_question_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='publish_date',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
