# Generated by Django 5.2.4 on 2025-09-23 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_alter_file_course'),
        ('tests', '0030_question_publish_date_question_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='content_type',
            field=models.CharField(choices=[('pdf', 'فایل PDF'), ('typed_question', 'سوال تایپ شده')], default='pdf', max_length=20, verbose_name='نوع محتوا'),
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='tests', to='tests.question', verbose_name='سوالات'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pdf_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_file', to='contents.file', verbose_name='فایل PDF'),
        ),
    ]
