# Generated by Django 5.2.4 on 2025-09-24 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0031_test_content_type_test_questions_alter_test_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedSolutionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='detailed_solution_images/', verbose_name='تصویر پاسخ تشریحی')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='متن جایگزین')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب تصویر')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_solution_images', to='tests.question', verbose_name='سوال مرتبط')),
            ],
            options={
                'verbose_name': 'تصویر پاسخ تشریحی',
                'verbose_name_plural': 'تصاویر پاسخ تشریحی',
                'ordering': ['order'],
            },
        ),
    ]
