# Generated by Django 5.2.4 on 2025-10-10 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0032_detailedsolutionimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام مجموعه سوال')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_question_collections', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('questions', models.ManyToManyField(related_name='collections', to='tests.question', verbose_name='سوالات')),
            ],
            options={
                'verbose_name': 'مجموعه سوال',
                'verbose_name_plural': 'مجموعه\u200cهای سوال',
                'ordering': ['-created_at'],
            },
        ),
    ]
