# Generated by Django 5.2.4 on 2025-10-22 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0033_questioncollection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testcollection',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='test_collections', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموزان مرتبط'),
        ),
    ]
