# Generated by Django 5.2.4 on 2025-10-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0034_testcollection_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcollection',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='دسترسی عمومی'),
        ),
    ]
