# Generated by Django 5.2.4 on 2025-11-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0035_testcollection_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttestsession',
            name='file_access_token',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True),
        ),
    ]
