# Generated by Django 5.2.4 on 2025-11-20 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_alter_folder_parent'),
        ('tests', '0036_studenttestsession_file_access_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام آزمون')),
                ('difficulty_level', models.CharField(blank=True, choices=[('easy', 'ساده'), ('medium', 'متوسط'), ('hard', 'دشوار')], max_length=10, null=True, verbose_name='سطح دشواری')),
                ('questions_count', models.PositiveIntegerField(verbose_name='تعداد سوالات')),
                ('duration', models.DurationField(verbose_name='مدت زمان آزمون')),
                ('status', models.CharField(choices=[('not_started', 'شروع نشده'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('expired', 'منقضی شده')], default='not_started', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نمره')),
                ('folders', models.ManyToManyField(blank=True, related_name='custom_tests', to='knowledge.folder', verbose_name='پوشه\u200cها')),
                ('questions', models.ManyToManyField(related_name='custom_tests', to='tests.question', verbose_name='سوالات')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='custom_tests', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'آزمون شخصی\u200cسازی شده',
                'verbose_name_plural': 'آزمون\u200cهای شخصی\u200cسازی شده',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='آخرین فعالیت')),
                ('custom_test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='tests.customtest', verbose_name='آزمون شخصی')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_test_sessions', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'جلسه آزمون شخصی',
                'verbose_name_plural': 'جلسات آزمون\u200cهای شخصی',
            },
        ),
        migrations.AddIndex(
            model_name='customtest',
            index=models.Index(fields=['student', 'status'], name='tests_custo_student_a1b973_idx'),
        ),
        migrations.AddIndex(
            model_name='customtest',
            index=models.Index(fields=['created_at'], name='tests_custo_created_e2de83_idx'),
        ),
    ]
