# Generated by Django 5.2.4 on 2025-11-20 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0037_customtest_customtestsession_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان پاسخ')),
                ('custom_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_answers', to='tests.customtest', verbose_name='آزمون شخصی')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_test_answers', to='tests.question', verbose_name='سوال')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.option', verbose_name='گزینه انتخاب شده')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_test_answers', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'پاسخ آزمون شخصی',
                'verbose_name_plural': 'پاسخ\u200cهای آزمون شخصی',
                'indexes': [models.Index(fields=['custom_test', 'student'], name='tests_custo_custom__abdbfa_idx'), models.Index(fields=['question'], name='tests_custo_questio_db185d_idx')],
                'unique_together': {('custom_test', 'student', 'question')},
            },
        ),
    ]
