"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from decouple import config, UndefinedValueError


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool, default=False)

# Server URLs
BACKEND_BASE_URL = config('BACKEND_BASE_URL')
FRONTEND_BASE_URL = config('FRONTEND_BASE_URL')

# For backward compatibility
if DEBUG:
    SERVER_IP = config('SERVER_IP', default=BACKEND_BASE_URL)
else:
    SERVER_IP = config('SERVER_IP', default=BACKEND_BASE_URL)

# Email settings
try:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = config('MAIL_HOST', default='smtp.gmail.com')
    EMAIL_PORT = int(config('MAIL_PORT', default=587))
    EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool, default=True)
    EMAIL_HOST_USER = config('MAIL_USER')
    EMAIL_HOST_PASSWORD = config('MAIL_PASSWORD')
    DEFAULT_FROM_EMAIL = config('MAIL_FROM_ADDRESS')
except UndefinedValueError:
    # Fallback for local dev: print emails to console
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'no-reply@localhost'

# SMS settings for sms.ir
SMS_IR_API_KEY = config('SMS_IR_API_KEY', default='')
SMS_IR_LINE_NUMBER = config('SMS_IR_LINE_NUMBER', default='')

# Zibal Payment Gateway Settings
# Use 'zibal' as merchant ID for sandbox/testing, or the real merchant ID for production
ZIBAL_MERCHANT_ID = config('ZIBAL_MERCHANT_ID', default='zibal')
ZIBAL_REQUEST_URL = 'https://gateway.zibal.ir/v1/request'
ZIBAL_VERIFY_URL = 'https://gateway.zibal.ir/v1/verify'
ZIBAL_INQUIRY_URL = 'https://gateway.zibal.ir/v1/inquiry'
ZIBAL_START_URL = 'https://gateway.zibal.ir/start/'  # append trackId

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')
# Allow Django test client default host when debugging
if DEBUG and 'testserver' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('testserver')

# CORS Settings - More restrictive for production
CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', cast=bool, default=False)
CORS_ALLOWED_ORIGINS = [
    origin.strip() for origin in config('CORS_ALLOWED_ORIGINS', 
    default="http://localhost:5173,http://127.0.0.1:5173").split(',')
]
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in config('CSRF_TRUSTED_ORIGINS', 
    default="http://localhost:5173,http://127.0.0.1:5173").split(',')
]
CORS_ALLOW_HEADERS = [
    "authorization",
    "content-type",
    "x-csrftoken",
    "x-requested-with",
    "accept",
    "accept-encoding",
    "accept-language",
    "access-control-request-headers",
    "access-control-request-method",
    "cache-control",
    "connection",
    "host",
    "origin",
    "pragma",
    "referer",
    "sec-fetch-dest",
    "sec-fetch-mode",
    "sec-fetch-site",
    "user-agent",
]
CORS_EXPOSE_HEADERS = ["Content-Disposition", "Content-Type"]
CORS_PREFLIGHT_MAX_AGE = 600

AUTH_USER_MODEL = 'accounts.User'

TIME_ZONE = 'Asia/Tehran'
USE_TZ = True

# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# HTTPS Settings (enable in production)
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', cast=bool, default=not DEBUG)
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', cast=int, default=31536000 if not DEBUG else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', cast=bool, default=not DEBUG)
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', cast=bool, default=not DEBUG)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', cast=bool, default=not DEBUG)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', cast=bool, default=not DEBUG)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if not DEBUG else None

# Session Security
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = config('SESSION_COOKIE_AGE', cast=int, default=86400)  # 24 hours
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
CSRF_COOKIE_HTTPONLY = True

# Cookie Domain Settings for Cross-Subdomain Authentication
if not DEBUG:
    SESSION_COOKIE_DOMAIN = '.ariantafazolizadeh.ir'
    CSRF_COOKIE_DOMAIN = '.ariantafazolizadeh.ir'
    SESSION_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_SAMESITE = 'None'
else:
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'
# Application definition

INSTALLED_APPS = [
    'daphne',
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.inlines',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    'rest_framework',
    'storages',
    'channels',

    'accounts',
    'courses',
    'contents',
    'tests',
    'shop',
    'finance',
    'spotplayer',
    'tickets',
    'knowledge',
    'blog',
    'chat',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'api.middleware.RefreshTokenMiddleware',
]

ROOT_URLCONF = 'api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'accounts' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

"""Parspack Object Storage settings (original working block)"""
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default=None)
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default=None)
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME', default=None)  # e.g. c242950
AWS_S3_REGION_NAME = 'default'  # ParsPack region placeholder
AWS_S3_ENDPOINT_URL = config('AWS_S3_ENDPOINT_URL', default=None)  # e.g. https://c242950.parspack.net
AWS_S3_CUSTOM_DOMAIN = ''  # disable custom domain for debug to avoid duplication and 403
AWS_S3_VERIFY = False
AWS_DEFAULT_ACL = None  # avoid sending ACL headers (BucketOwnerEnforced scenarios)
AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
AWS_S3_FILE_OVERWRITE = True  # skip exists() HEAD to reduce 403 surface
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_ADDRESSING_STYLE = 'path'  # match typical S3 Browser default
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
FILE_UPLOAD_MAX_MEMORY_SIZE = 0  # always use disk

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "bucket_name": AWS_STORAGE_BUCKET_NAME,
            "endpoint_url": AWS_S3_ENDPOINT_URL,
            "access_key": AWS_ACCESS_KEY_ID,
            "secret_key": AWS_SECRET_ACCESS_KEY,
            "region_name": AWS_S3_REGION_NAME,
            "file_overwrite": AWS_S3_FILE_OVERWRITE,
            "default_acl": AWS_DEFAULT_ACL,
            "object_parameters": AWS_S3_OBJECT_PARAMETERS,
            "verify": AWS_S3_VERIFY,
            "location": "media",
            "addressing_style": AWS_S3_ADDRESSING_STYLE,
            "signature_version": AWS_S3_SIGNATURE_VERSION,
        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File Upload Security
FILE_UPLOAD_PERMISSIONS = 0o644
DATA_UPLOAD_MAX_MEMORY_SIZE = config('DATA_UPLOAD_MAX_MEMORY_SIZE', cast=int, default=10*5242880)  # 5MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = config('DATA_UPLOAD_MAX_NUMBER_FIELDS', cast=int, default=1000)
DATA_UPLOAD_MAX_NUMBER_FILES = config('DATA_UPLOAD_MAX_NUMBER_FILES', cast=int, default=500)

WSGI_APPLICATION = 'api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration with environment variables
_db_engine = config('DB_ENGINE', default='django.db.backends.sqlite3')

if _db_engine == 'django.db.backends.sqlite3':
    _db_options = {
        'timeout': 30,  # Wait up to 30s for lock instead of failing immediately
    }
elif _db_engine.startswith('django.db.backends.mysql'):
    _db_options = {
        'charset': 'utf8mb4',
    }
else:
    _db_options = {}

DATABASES = {
    'default': {
        'ENGINE': _db_engine,
        'NAME': config('DB_NAME', default=str(BASE_DIR / 'db.sqlite3')),
        'USER': config('DB_USER', default=''),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default=''),
        'PORT': config('DB_PORT', default=''),
        'OPTIONS': _db_options,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.auth.CookieJWTAuthentication',
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': config('THROTTLE_ANON_RATE', default='100/hour'),
        'user': config('THROTTLE_USER_RATE', default='1000/hour')
    },
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': config('API_PAGE_SIZE', cast=int, default=20)
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=config('JWT_ACCESS_TOKEN_LIFETIME_MINUTES', cast=int, default=15)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=config('JWT_REFRESH_TOKEN_LIFETIME_DAYS', cast=int, default=7)),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': config('JWT_SIGNING_KEY', default=SECRET_KEY),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
}

# SpotPlayer DRM Settings
# https://spotplayer.ir/ — API key is copied from the panel dashboard
SPOTPLAYER_API_KEY = config('SPOTPLAYER_API_KEY', default='')
SPOTPLAYER_API_BASE_URL = config('SPOTPLAYER_API_BASE_URL', default='https://panel.spotplayer.ir')
SPOTPLAYER_DL_DOMAIN = config('SPOTPLAYER_DL_DOMAIN', default='https://dl.spotplayer.ir')
SPOTPLAYER_APP_URL = config('SPOTPLAYER_APP_URL', default='https://app.spotplayer.ir')
SPOTPLAYER_API_TIMEOUT = config('SPOTPLAYER_API_TIMEOUT', cast=int, default=15)
# When True, all newly created licenses are test licenses ("test": true)
SPOTPLAYER_TEST_MODE = config('SPOTPLAYER_TEST_MODE', cast=bool, default=False)
# Custom cookie name if the default 'X' is already used on your domain
SPOTPLAYER_COOKIE_NAME = config('SPOTPLAYER_COOKIE_NAME', default='X')

# API Keys - Use environment variables
try:
    from dotenv import load_dotenv
    # Load API keys from .env file
    env_path = os.path.join(BASE_DIR, 'api_keys', '.env')
    load_dotenv(dotenv_path=env_path)
    GOOGLE_API_KEY = config('GOOGLE_API_KEY')
    LIARA_API_KEY = config('LIARA_API_KEY')
    LLM_API_KEY = config('LLM_API_KEY')
    LLM_BASE_URL = config('LLM_BASE_URL', default='https://arvancloudai.ir/gateway/models/DeepSeek-V4-Pro/XDSfG8DZnRv7J3fkDqL-w0BgaO__UP8UvQj3lJvG9IZCGm-wENAH5nIRVPrrsk7rnM8ddC7ZIcL_aNxBpRTfRmNy7X3N3CKEiKc4Rzol8liTH7WDcDovs3YQmVqUfWdXWvoWy9yTENirsPA6Wdbk2wq1DsOBFJbfP9yQh9Qfv8xArG7Q3RqqBr3XnhR-8QzWYmBe8dLF4l7spJYnp0s6ES9Y1-qWpB3vTZaTwvcGPEWcrIB6uWDhNXeWXeNcsxJteDJy1A/v1')
    LLM_MODEL = config('LLM_MODEL', default='DeepSeek-V4-Pro')
except (ImportError, UndefinedValueError):
    GOOGLE_API_KEY = config('GOOGLE_API_KEY', default='')
    LIARA_API_KEY = config('LIARA_API_KEY', default='')
    LLM_API_KEY = config('LLM_API_KEY', default='')
    LLM_BASE_URL = config('LLM_BASE_URL', default='https://arvancloudai.ir/gateway/models/DeepSeek-V4-Pro/XDSfG8DZnRv7J3fkDqL-w0BgaO__UP8UvQj3lJvG9IZCGm-wENAH5nIRVPrrsk7rnM8ddC7ZIcL_aNxBpRTfRmNy7X3N3CKEiKc4Rzol8liTH7WDcDovs3YQmVqUfWdXWvoWy9yTENirsPA6Wdbk2wq1DsOBFJbfP9yQh9Qfv8xArG7Q3RqqBr3XnhR-8QzWYmBe8dLF4l7spJYnp0s6ES9Y1-qWpB3vTZaTwvcGPEWcrIB6uWDhNXeWXeNcsxJteDJy1A/v1')
    LLM_MODEL = config('LLM_MODEL', default='DeepSeek-V4-Pro')

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'request': {
            'format': '{asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'request_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'requests.log',
            'formatter': 'request',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console', 'request_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'request_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
os.makedirs(BASE_DIR / 'logs', exist_ok=True)

# ASGI & Channels Settings
ASGI_APPLICATION = 'api.asgi.application'

# InMemoryChannelLayer works fine with a single Daphne process.
# If you ever scale to multiple workers, switch to RedisChannelLayer:
#   'BACKEND': 'channels_redis.core.RedisChannelLayer',
#   'CONFIG': {"hosts": [(config('REDIS_HOST', default='127.0.0.1'), 6379)]},
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}


# ---------------------------------------------------------------------------
# SQLite WAL mode — enable Write-Ahead Logging for every new connection.
# WAL lets readers and one writer work simultaneously, preventing most
# "database is locked" errors under concurrent exam traffic.
# This has no effect when using PostgreSQL/MySQL in production.
# ---------------------------------------------------------------------------
if _db_engine == 'django.db.backends.sqlite3':
    from django.db.backends.signals import connection_created

    def _enable_sqlite_wal(sender, connection, **kwargs):
        if connection.vendor == 'sqlite':
            connection.cursor().execute('PRAGMA journal_mode=WAL;')
            connection.cursor().execute('PRAGMA synchronous=NORMAL;')
            connection.cursor().execute('PRAGMA cache_size=-8000;')  # 8 MB cache

    connection_created.connect(_enable_sqlite_wal)


# ---------------------------------------------------------------------------
# Django Unfold (Tailwind CSS Admin) Settings
# ---------------------------------------------------------------------------
from django.templatetags.static import static
from django.urls import reverse_lazy

UNFOLD = {
    "SITE_TITLE": "Academia Admin",
    "SITE_HEADER": "Academia Admin",
    "SITE_SUBHEADER": "Education & Exam Management Platform",
    "SITE_URL": "/",
    "SITE_SYMBOL": "school",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "STYLES": [
        lambda request: "https://fonts.googleapis.com/css2?family=Vazirmatn:wght@100..900&display=swap",
        lambda request: "https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200",
        lambda request: static("css/admin_custom.css"),
    ],
    "SCRIPTS": [],
    "COLORS": {
        # "primary": {
        #     "50": "245 243 255",
        #     "100": "237 233 254",
        #     "200": "221 214 254",
        #     "300": "196 181 253",
        #     "400": "167 139 250",
        #     "500": "139 92 246",
        #     "600": "124 58 237",
        #     "700": "109 40 217",
        #     "800": "91 33 182",
        #     "900": "76 29 149",
        #     "950": "46 16 101",
        # },
        "primary": {
            "50": "239 246 255",
            "100": "219 234 254",
            "200": "191 219 254",
            "300": "147 197 253",
            "400": "96 165 250",
            "500": "59 130 246",
            "600": "37 99 235",
            "700": "29 78 216",
            "800": "30 64 175",
            "900": "30 58 138",
            "950": "23 37 84",
        },
        "base": {
            "50": "250 250 250",
            "100": "244 244 245",
            "200": "228 228 231",
            "300": "212 212 216",
            "400": "161 161 170",
            "500": "113 113 122",
            "600": "82 82 91",
            "700": "63 63 70",
            "800": "39 39 42",
            "900": "24 24 27",
            "950": "9 9 11",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Users & Access",
                "separator": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "group",
                        "link": reverse_lazy("admin:accounts_user_changelist"),
                    },
                    {
                        "title": "User Profiles",
                        "icon": "badge",
                        "link": reverse_lazy("admin:accounts_userprofile_changelist"),
                    },
                    {
                        "title": "Verification Codes",
                        "icon": "pin",
                        "link": reverse_lazy("admin:accounts_verificationcode_changelist"),
                    },
                    {
                        "title": "AI Access",
                        "icon": "psychology",
                        "link": reverse_lazy("admin:accounts_aiaccess_changelist"),
                    },
                ],
            },
            {
                "title": "Courses & Education",
                "separator": True,
                "items": [
                    {
                        "title": "Courses",
                        "icon": "school",
                        "link": reverse_lazy("admin:courses_course_changelist"),
                    },
                    {
                        "title": "Class Categories",
                        "icon": "category",
                        "link": reverse_lazy("admin:courses_classcategory_changelist"),
                    },
                    {
                        "title": "Course Sessions",
                        "icon": "video_library",
                        "link": reverse_lazy("admin:courses_coursesession_changelist"),
                    },
                    {
                        "title": "Class Schedules",
                        "icon": "calendar_month",
                        "link": reverse_lazy("admin:courses_courseschedule_changelist"),
                    },
                    {
                        "title": "SpotPlayer Licenses",
                        "icon": "key",
                        "link": reverse_lazy("admin:spotplayer_spotplayerlicense_changelist"),
                    },
                ],
            },
            {
                "title": "Tests & Exams",
                "separator": True,
                "items": [
                    {
                        "title": "Test Collections",
                        "icon": "folder_special",
                        "link": reverse_lazy("admin:tests_testcollection_changelist"),
                    },
                    {
                        "title": "Tests",
                        "icon": "quiz",
                        "link": reverse_lazy("admin:tests_test_changelist"),
                    },
                    {
                        "title": "Question Bank",
                        "icon": "help_outline",
                        "link": reverse_lazy("admin:tests_question_changelist"),
                    },
                    {
                        "title": "Student Test Sessions",
                        "icon": "assignment_ind",
                        "link": reverse_lazy("admin:tests_studenttestsession_changelist"),
                    },
                    {
                        "title": "Student Progress",
                        "icon": "trending_up",
                        "link": reverse_lazy("admin:tests_studentprogress_changelist"),
                    },
                    {
                        "title": "Custom Tests",
                        "icon": "tune",
                        "link": reverse_lazy("admin:tests_customtest_changelist"),
                    },
                ],
            },
            {
                "title": "Finance & Shop",
                "separator": True,
                "items": [
                    {
                        "title": "Shop Products",
                        "icon": "shopping_bag",
                        "link": reverse_lazy("admin:shop_product_changelist"),
                    },
                    {
                        "title": "Discounts",
                        "icon": "local_offer",
                        "link": reverse_lazy("admin:shop_discount_changelist"),
                    },
                    {
                        "title": "Orders",
                        "icon": "receipt_long",
                        "link": reverse_lazy("admin:finance_order_changelist"),
                    },
                    {
                        "title": "Transactions",
                        "icon": "account_balance_wallet",
                        "link": reverse_lazy("admin:finance_transaction_changelist"),
                    },
                    {
                        "title": "Zibal Payments",
                        "icon": "payments",
                        "link": reverse_lazy("admin:finance_payment_changelist"),
                    },
                    {
                        "title": "User Access",
                        "icon": "lock_open",
                        "link": reverse_lazy("admin:finance_useraccess_changelist"),
                    },
                    {
                        "title": "SMS Config",
                        "icon": "sms",
                        "link": reverse_lazy("admin:finance_smsnotificationconfig_changelist"),
                    },
                ],
            },
            {
                "title": "Content & Blog",
                "separator": True,
                "items": [
                    {
                        "title": "Blog Posts",
                        "icon": "article",
                        "link": reverse_lazy("admin:blog_post_changelist"),
                    },
                    {
                        "title": "Blog Categories",
                        "icon": "folder",
                        "link": reverse_lazy("admin:blog_category_changelist"),
                    },
                    {
                        "title": "Blog Comments",
                        "icon": "comment",
                        "link": reverse_lazy("admin:blog_comment_changelist"),
                    },
                    {
                        "title": "Knowledge Subjects",
                        "icon": "menu_book",
                        "link": reverse_lazy("admin:knowledge_subject_changelist"),
                    },
                    {
                        "title": "Knowledge Topics",
                        "icon": "topic",
                        "link": reverse_lazy("admin:knowledge_topic_changelist"),
                    },
                    {
                        "title": "Files & Media",
                        "icon": "attachment",
                        "link": reverse_lazy("admin:contents_file_changelist"),
                    },
                    {
                        "title": "Gallery Images",
                        "icon": "photo_library",
                        "link": reverse_lazy("admin:contents_galleryimage_changelist"),
                    },
                ],
            },
            {
                "title": "Support & Tickets",
                "separator": True,
                "items": [
                    {
                        "title": "Tickets",
                        "icon": "support_agent",
                        "link": reverse_lazy("admin:tickets_ticket_changelist"),
                    },
                    {
                        "title": "Ticket Responses",
                        "icon": "reply",
                        "link": reverse_lazy("admin:tickets_ticketresponse_changelist"),
                    },
                ],
            },
        ],
    },
}

