# Generated by Django 5.2.4 on 2026-08-01 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0013_course_spotplayer_course_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotPlayerLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotplayer_license_id', models.CharField(blank=True, max_length=64, null=True)),
                ('spotplayer_license_key', models.TextField(blank=True, null=True)),
                ('spotplayer_url', models.CharField(blank=True, help_text='Relative video URL returned by SpotPlayer (e.g. /5e07...ff/).', max_length=255, null=True)),
                ('watermark_text', models.CharField(blank=True, max_length=255, null=True)),
                ('test_mode', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotplayer_licenses', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotplayer_licenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SpotPlayer License',
                'verbose_name_plural': 'SpotPlayer Licenses',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
